title: Michael Popa
theme: jekyll-theme-minimal

logo: "/images/linkedin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Biomedical researcher with experience in data analysis, machine learning, and biomarker discovery. Passionate about applying AI methodologies in the field of medicine and healthcare to improve patient treatment.
  <br><br>
  Studied the blend of cognitive sciences, neuroscience, and data science at Rice University in Houston, TX.
  <br><br>
  <a href="https://www.linkedin.com/in/michaelpopa01">View my LinkedIn Profile</a> 
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
